using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Text.RegularExpressions;
using Newtonsoft.Json.Linq;

namespace GxMcp.Worker.Tests
{
    // Executes the SQL generated by the adapter against transaction-local rows.
    // It deliberately supports only that SQL subset, and rejects anything else.
    internal sealed class TransactionRecordsFakeDatabase : DbProviderFactory
    {
        internal List<JObject> Rows = new List<JObject>();
        internal readonly List<string> Commands = new List<string>();
        internal readonly Dictionary<string, DbType> OutputParameterTypes = new Dictionary<string, DbType>();
        internal int SelectedRows, Selects, Writes, Transactions, Commits, Rollbacks;
        internal int ScalarCalls, NonQueryCalls;
        internal object TriggerScalarResult, GeneratedKeyOverride;
        internal int? NonQueryReturnOverride;
        internal bool OmitOutputParameters;
        internal long NextId = 1000001;
        internal bool ThrowBeforeCommit, ThrowAfterCommit, ThrowRollback, FailRestore;
        internal Action<TransactionRecordsFakeDatabase> AfterCommit;
        internal Action<TransactionRecordsFakeDatabase, int> BeforeSelect;
        internal Func<JObject, JObject> Trigger;
        internal List<JObject> OverrideRead;
        internal string Server = "synthetic-server", Catalog = "synthetic-db";

        public override DbConnection CreateConnection() => new Connection(this);
        internal void ResetCounters()
        {
            Commands.Clear();
            SelectedRows = Selects = Writes = Transactions = Commits = Rollbacks = 0;
            ScalarCalls = NonQueryCalls = 0;
            OutputParameterTypes.Clear();
        }
        internal static JObject Row(long id, string value = "old", long stamp = 0)
            => new JObject { ["Id"] = id, ["Value"] = value, ["Stamp"] = stamp };
        private static List<JObject> Copy(IEnumerable<JObject> rows) => rows.Select(r => (JObject)r.DeepClone()).ToList();

        private sealed class Connection : DbConnection
        {
            internal readonly TransactionRecordsFakeDatabase Db;
            private ConnectionState _state;
            internal Connection(TransactionRecordsFakeDatabase db) { Db = db; }
            public override string ConnectionString { get; set; }
            public override string Database => Db.Catalog;
            public override string DataSource => Db.Server;
            public override string ServerVersion => "1";
            public override ConnectionState State => _state;
            public override void ChangeDatabase(string databaseName) => throw new NotSupportedException();
            public override void Open() { _state = ConnectionState.Open; }
            public override void Close() { _state = ConnectionState.Closed; }
            protected override DbCommand CreateDbCommand() => new Command(this);
            protected override DbTransaction BeginDbTransaction(IsolationLevel isolationLevel)
            {
                if (isolationLevel != IsolationLevel.Serializable) throw new InvalidOperationException("Isolation level changed.");
                Db.Transactions++;
                return new Transaction(this);
            }
        }

        private sealed class Transaction : DbTransaction
        {
            private readonly Connection _connection;
            private readonly List<JObject> _before;
            private bool _ended;
            internal Transaction(Connection connection) { _connection = connection; _before = Copy(connection.Db.Rows); }
            public override IsolationLevel IsolationLevel => IsolationLevel.Serializable;
            protected override DbConnection DbConnection => _connection;
            public override void Commit()
            {
                var db = _connection.Db;
                if (db.ThrowBeforeCommit) throw new FakeDbException();
                _ended = true;
                db.Commits++;
                db.AfterCommit?.Invoke(db);
                if (db.ThrowAfterCommit) throw new FakeDbException();
            }
            public override void Rollback()
            {
                if (_ended) return;
                if (_connection.Db.ThrowRollback) throw new FakeDbException();
                _connection.Db.Rows = Copy(_before);
                _connection.Db.Rollbacks++;
                _ended = true;
            }
            protected override void Dispose(bool disposing) { if (disposing && !_ended) Rollback(); base.Dispose(disposing); }
        }

        private sealed class Command : DbCommand
        {
            private readonly Connection _connection;
            private readonly Parameters _parameters = new Parameters();
            internal Command(Connection connection) { _connection = connection; }
            public override string CommandText { get; set; }
            public override int CommandTimeout { get; set; }
            public override CommandType CommandType { get; set; }
            public override bool DesignTimeVisible { get; set; }
            public override UpdateRowSource UpdatedRowSource { get; set; }
            protected override DbConnection DbConnection { get => _connection; set { } }
            protected override DbTransaction DbTransaction { get; set; }
            protected override DbParameterCollection DbParameterCollection => _parameters;
            protected override DbParameter CreateDbParameter() => new Parameter();
            public override void Cancel() => throw new NotSupportedException();
            public override void Prepare() { }
            private JToken Value(string name)
            {
                object value = _parameters.Cast<DbParameter>().Single(p => p.ParameterName == name).Value;
                return value == DBNull.Value ? JValue.CreateNull() : JToken.FromObject(value);
            }
            private bool Matches(JObject row)
            {
                int where = CommandText.IndexOf(" WHERE ", StringComparison.Ordinal);
                if (where < 0) return true;
                string predicate = CommandText.Substring(where + 7);
                foreach (string clause in predicate.Split(new[] { " AND " }, StringSplitOptions.None))
                {
                    var match = Regex.Match(clause, @"^\[(\w+)\](?:=(@\w+)|( IS NULL))$");
                    if (!match.Success) throw new NotSupportedException("Unexpected predicate: " + clause);
                    var expected = match.Groups[3].Success ? JValue.CreateNull() : Value(match.Groups[2].Value);
                    if (row[match.Groups[1].Value].ToString() != expected.ToString()) return false;
                }
                return true;
            }
            protected override DbDataReader ExecuteDbDataReader(CommandBehavior behavior)
            {
                var db = _connection.Db;
                db.Commands.Add(CommandText);
                db.Selects++;
                db.BeforeSelect?.Invoke(db, db.Selects);
                var match = Regex.Match(CommandText, @"^SELECT (?:TOP (\d+) )?(.+) FROM \[.+?\](?:\.\[.+?\])?(?: WHERE .+)?$");
                if (!match.Success) throw new NotSupportedException("Unexpected select: " + CommandText);
                int limit = match.Groups[1].Success ? int.Parse(match.Groups[1].Value) : int.MaxValue;
                string[] fields = match.Groups[2].Value.Split(',').Select(s => s.Trim().Trim('[', ']')).ToArray();
                var selected = db.OverrideRead ?? db.Rows.Where(Matches).Take(limit).ToList();
                db.OverrideRead = null;
                db.SelectedRows += selected.Count;
                var table = new DataTable();
                foreach (string field in fields) table.Columns.Add(field, typeof(object));
                foreach (var row in selected)
                    table.Rows.Add(fields.Select(f => row[f].Type == JTokenType.Null ? DBNull.Value
                        : f == "Id" && (row[f].Type == JTokenType.Integer || (row[f] as JValue)?.Value is decimal)
                            ? (object)row[f].Value<long>() : row[f].ToObject<object>()).ToArray());
                return table.CreateDataReader();
            }
            private int Mutate(out object key)
            {
                var db = _connection.Db;
                if (DbTransaction == null) throw new InvalidOperationException("Write outside transaction.");
                db.Commands.Add(CommandText);
                db.Writes++;
                key = null;
                if (CommandText.StartsWith("INSERT ", StringComparison.Ordinal) || CommandText.StartsWith("DECLARE @generatedKeys ", StringComparison.Ordinal))
                {
                    var match = Regex.Match(CommandText, @"\(([^)]+)\)(?: OUTPUT INSERTED\.\[(\w+)\] INTO @generatedKeys \(Value\))? VALUES \(([^)]+)\)(?:; SELECT Value FROM @generatedKeys)?$");
                    if (!match.Success) throw new NotSupportedException(CommandText);
                    var names = match.Groups[1].Value.Split(',').Select(s => s.Trim().Trim('[', ']')).ToArray();
                    var parameters = match.Groups[3].Value.Split(',').Select(s => s.Trim()).ToArray();
                    var row = Row(db.NextId++, "", 0);
                    if (db.GeneratedKeyOverride != null) row["Id"] = JToken.FromObject(db.GeneratedKeyOverride);
                    for (int i = 0; i < names.Length; i++) row[names[i]] = Value(parameters[i]);
                    if (db.Rows.Any(r => r["Id"].ToString() == row["Id"].ToString())) throw new FakeDbException();
                    if (db.Trigger != null) row = db.Trigger(row);
                    db.Rows.Add(row);
                    key = row["Id"].ToObject<object>();
                    return 1;
                }
                var affected = db.Rows.Where(Matches).ToList();
                if (CommandText.StartsWith("DELETE ", StringComparison.Ordinal))
                {
                    foreach (var row in affected) db.Rows.Remove(row);
                    return affected.Count;
                }
                if (!CommandText.StartsWith("UPDATE ", StringComparison.Ordinal)) throw new NotSupportedException(CommandText);
                if (db.FailRestore && CommandText.Contains("@r0")) throw new FakeDbException();
                int start = CommandText.IndexOf(" SET ", StringComparison.Ordinal) + 5;
                int end = CommandText.IndexOf(" WHERE ", StringComparison.Ordinal);
                var assignments = CommandText.Substring(start, end - start).Split(',');
                foreach (var row in affected)
                {
                    foreach (string assignment in assignments)
                    {
                        var match = Regex.Match(assignment.Trim(), @"^\[(\w+)\]=(@\w+)$");
                        if (!match.Success) throw new NotSupportedException(assignment);
                        row[match.Groups[1].Value] = Value(match.Groups[2].Value);
                    }
                    if (db.Trigger != null)
                    {
                        var triggered = db.Trigger((JObject)row.DeepClone());
                        row.RemoveAll();
                        foreach (var property in triggered.Properties()) row[property.Name] = property.Value.DeepClone();
                    }
                }
                return affected.Count;
            }
            private int ExecuteMutation(out object key)
            {
                const string affectedSuffix = "; SET @affectedRows = @@ROWCOUNT";
                const string generatedSuffix = "; SELECT @generatedKey = Value FROM @generatedKeys";
                string original = CommandText;
                bool affected = original.EndsWith(affectedSuffix, StringComparison.Ordinal);
                bool generated = original.EndsWith(generatedSuffix, StringComparison.Ordinal);
                // SQL Server rejects this assignment before executing the batch
                // (error 257). Do not let the fake silently coerce a variant key.
                if (generated && Regex.IsMatch(original, @"DECLARE\s+@generatedKeys\s+TABLE\s*\(Value\s+sql_variant\s*\)", RegexOptions.IgnoreCase))
                {
                    var output = _parameters.Cast<DbParameter>().Single(p => p.ParameterName == "@generatedKey");
                    if (output.DbType != DbType.Object) throw new FakeDbException(257);
                }
                if (affected) CommandText = original.Substring(0, original.Length - affectedSuffix.Length);
                if (generated) CommandText = original.Substring(0, original.Length - generatedSuffix.Length);
                int count = Mutate(out key);
                _connection.Db.Commands[_connection.Db.Commands.Count - 1] = original;
                CommandText = original;
                if (affected || generated)
                {
                    var output = _parameters.Cast<DbParameter>().Single(p => p.ParameterName == (affected ? "@affectedRows" : "@generatedKey"));
                    if (output.Direction != ParameterDirection.Output) throw new InvalidOperationException("Expected output parameter.");
                    if (affected && output.DbType != DbType.Int32) throw new InvalidOperationException("Expected typed row count.");
                    if (generated && output.DbType == DbType.String && output.Size <= 0) throw new InvalidOperationException("Output strings require size.");
                    _connection.Db.OutputParameterTypes[output.ParameterName] = output.DbType;
                    if (!_connection.Db.OmitOutputParameters)
                        output.Value = affected ? (object)count : key;
                }
                return count;
            }
            public override int ExecuteNonQuery()
            {
                _connection.Db.NonQueryCalls++;
                object key;
                int count = ExecuteMutation(out key);
                // ADO ignores result-set values here, but its return count can be
                // -1 (NOCOUNT) or include trigger DML counts. Neither is authoritative.
                return _connection.Db.NonQueryReturnOverride ?? count;
            }
            public override object ExecuteScalar()
            {
                _connection.Db.ScalarCalls++;
                object key;
                int count = ExecuteMutation(out key);
                // Model the reviewed failure: a trigger's SELECT is first, even
                // though the correct output parameters were populated afterward.
                return _connection.Db.TriggerScalarResult ?? key ?? (object)count;
            }
        }

        internal sealed class FakeDbException : DbException
        {
            internal readonly int Number;
            internal FakeDbException(int number = 0)
                : base(number == 257 ? "Implicit conversion from sql_variant to a typed output parameter is not allowed." : "SYNTHETIC_SECRET_DO_NOT_RETURN")
            { Number = number; }
        }
        private sealed class Parameter : DbParameter
        {
            public override DbType DbType { get; set; }
            public override ParameterDirection Direction { get; set; }
            public override bool IsNullable { get; set; }
            public override string ParameterName { get; set; }
            public override string SourceColumn { get; set; }
            public override object Value { get; set; }
            public override bool SourceColumnNullMapping { get; set; }
            public override int Size { get; set; }
            public override byte Precision { get; set; }
            public override byte Scale { get; set; }
            public override void ResetDbType() { }
        }
        private sealed class Parameters : DbParameterCollection
        {
            private readonly List<DbParameter> _items = new List<DbParameter>();
            public override int Count => _items.Count;
            public override object SyncRoot => this;
            public override int Add(object value) { _items.Add((DbParameter)value); return _items.Count - 1; }
            public override void AddRange(Array values) { foreach (var value in values) Add(value); }
            public override void Clear() => _items.Clear();
            public override bool Contains(object value) => _items.Contains((DbParameter)value);
            public override bool Contains(string value) => IndexOf(value) >= 0;
            public override void CopyTo(Array array, int index) => ((ICollection)_items).CopyTo(array, index);
            public override IEnumerator GetEnumerator() => _items.GetEnumerator();
            public override int IndexOf(object value) => _items.IndexOf((DbParameter)value);
            public override int IndexOf(string name) => _items.FindIndex(p => p.ParameterName == name);
            public override void Insert(int index, object value) => _items.Insert(index, (DbParameter)value);
            public override void Remove(object value) => _items.Remove((DbParameter)value);
            public override void RemoveAt(int index) => _items.RemoveAt(index);
            public override void RemoveAt(string name) => RemoveAt(IndexOf(name));
            protected override DbParameter GetParameter(int index) => _items[index];
            protected override DbParameter GetParameter(string name) => _items[IndexOf(name)];
            protected override void SetParameter(int index, DbParameter value) => _items[index] = value;
            protected override void SetParameter(string name, DbParameter value) => _items[IndexOf(name)] = value;
        }
    }
}
